version: 1.0.{build}
branches:
  only:
  - master
  - dev-tests
  - appveyor
skip_tags: true
image: Visual Studio 2017
platform:
  - x86
  - x64
configuration:
  - Release
before_build:
  - nuget restore msvc\corehook.sln
build:
  project: msvc\corehook.sln
skip_commits:
  files:
    - '**/*.md'
after_build:
  7z a corehook.zip %APPVEYOR_BUILD_FOLDER%\*\Release\*.dll
artifacts:
- path: corehook.zip
  name: Releases
deploy:
  provider: GitHub
  description: "corehook detour deployment"
  auth_token:
    secure: 99ssBJ/lNK6AL1FNajtOhloP5bXeUAm8m+cI0us6pW1hVw84MTKxwYzfurYMuaOQ
  draft: false
  prerelease: false
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    appveyor_repo_tag: true