version: 1.0.{build}
branches:
  only:
  - master
  - dev-tests
  - appveyor

image: Visual Studio 2017
platform:
  - x86
  - x64
  - ARM
  - ARM64
configuration:
  - Debug
  - Release
before_build:
  - nuget restore msvc\corehook.sln
build:
  project: msvc\corehook.sln
skip_commits:
  files:
    - '**/*.md'
after_build:
  7z a corehook-%CONFIGURATION%-%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\*\%CONFIGURATION%\corehook*.dll
 
artifacts:
- path: corehook-%CONFIGURATION%-%PLATFORM%.zip
  name: Releases

deploy:
  provider: GitHub
  description: "corehook detour deployment"
  auth_token:
    secure: 99ssBJ/lNK6AL1FNajtOhloP5bXeUAm8m+cI0us6pW1hVw84MTKxwYzfurYMuaOQ
  draft: false
  prerelease: false
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    appveyor_repo_tag: true